
"""create student and employer tables

Revision ID: 31ee817b15eb
Revises: 
Create Date: 2026-07-14 16:12:48.491590

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '31ee817b15eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'employer', 'mentor', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('MENTOR',
    sa.Column('mentorId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('expertise', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mentorId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('resume_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('INTERNSHIP',
    sa.Column('internshipId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.BigInteger(), nullable=False),
    sa.Column('mentorId', sa.BigInteger(), nullable=False),
    sa.Column('employerId', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['employerId'], ['employers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentorId'], ['MENTOR.mentorId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internshipId')
    )
    op.create_table('CERTIFICATE',
    sa.Column('certificateId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internshipId', sa.BigInteger(), nullable=False),
    sa.Column('issueDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['internshipId'], ['INTERNSHIP.internshipId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificateId'),
    sa.UniqueConstraint('internshipId')
    )
    op.create_table('TASK',
    sa.Column('taskId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internshipId', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['internshipId'], ['INTERNSHIP.internshipId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.create_table('SUBMISSION',
    sa.Column('submissionId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('taskId', sa.BigInteger(), nullable=False),
    sa.Column('studentId', sa.BigInteger(), nullable=False),
    sa.Column('fileUrl', sa.String(length=1000), nullable=False),
    sa.Column('submittedDate', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taskId'], ['TASK.taskId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submissionId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SUBMISSION')
    op.drop_table('TASK')
    op.drop_table('CERTIFICATE')
    op.drop_table('INTERNSHIP')
    op.drop_table('students')
    op.drop_table('employers')
    op.drop_table('MENTOR')
    op.drop_table('users')
    # ### end Alembic commands ###
